services:
  postgres-vector:
    image: pgvector/pgvector:pg16
    container_name: medical_pgvector
    environment:
      POSTGRES_DB: appointment
      POSTGRES_USER: root
      POSTGRES_PASSWORD: fc100711
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./script_BD:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d appointment"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rag_network

  medical-rag-api:
    build:
      context: . # El contexto es la raíz del proyecto
      dockerfile: Dockerfile # El Dockerfile está en la raíz del proyecto
    container_name: medical_rag_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    extra_hosts:
      - "host.containers.internal:host-gateway"
      - "host.docker.internal:host-gateway"
    environment:
      # Conexión con Ollama en el Host (Linux / Podman / Docker)
      - OLLAMA_BASE_URL=http://host.containers.internal:11434
      - LLM_MODEL=llama3.2:latest
      - EMBEDDING_MODEL=nomic-embed-text:latest
      # Conexión asíncrona con PostgreSQL (asyncpg)
      - DATABASE_URL=postgresql+asyncpg://root:fc100711@postgres-vector:5432/appointment
    depends_on:
      postgres-vector:
        condition: service_healthy
    networks:
      - rag_network

volumes:
  pgvector_data:

networks:
  rag_network:
    driver: bridge