services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/med_appointment
      SECRET_KEY: med-appointments-secret-key-change-in-production
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      REFRESH_TOKEN_EXPIRE_DAYS: 7
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: med_appointment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./front:/app
      - /app/node_modules

volumes:
  pg_data:
